

function Inversiones() {
    return (
        <section id='inversiones' className='padded'>
            <div className="container">
                <h2>Inversiones</h2>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi accusamus asperiores soluta natus porro quod minima pariatur delectus voluptate sint doloribus corporis nemo aperiam saepe velit rerum distinctio odit suscipit dolorem, at facere veniam deleniti! Voluptate modi facilis voluptates temporibus aperiam qui! Quae quam natus fugiat maiores at, voluptatum magni veniam deleniti sequi harum? Odio velit, dolorum magni voluptates voluptas consequatur rerum numquam in laboriosam facere possimus at incidunt, enim, voluptatibus sint voluptate iste libero eum laudantium! Modi illo eum minus dicta. Tempore tenetur, reprehenderit, cumque aliquam hic libero nihil exercitationem ex et soluta esse pariatur doloribus debitis provident culpa ullam voluptatem distinctio qui dolore fugiat! Quam nostrum iusto expedita voluptatum quas cumque, impedit magni nisi, voluptate, eos delectus doloribus.</p>
                <p>Nesciunt debitis modi facere architecto molestiae corporis, pariatur dolorum quis quia dolore quas obcaecati eius ea dicta voluptatum mollitia, itaque porro reiciendis repellendus, ullam incidunt. Perferendis, expedita esse laboriosam ex a voluptate officia quam at voluptas quae tenetur sed reiciendis dolorem autem officiis quod laborum odit quas excepturi odio! Cupiditate et a voluptate numquam laudantium rem vel laboriosam provident, dolorem quos labore neque ab! Ratione tempore modi in accusamus repellat corporis, cumque est suscipit, quo harum eaque nobis mollitia reprehenderit adipisci obcaecati vitae tenetur perferendis sequi? Maxime doloribus fugit officia provident magnam odit possimus dolore expedita nobis praesentium, perspiciatis quae aliquam ipsam nostrum esse excepturi rem iure neque velit aperiam nihil inventore id? Numquam cum velit a! Earum, laboriosam tenetur?</p>
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ullam accusamus iusto quidem, corporis rem numquam perferendis praesentium quae, impedit, deleniti consequatur autem ipsam veniam aliquam architecto at nam quo deserunt incidunt soluta? Cupiditate, quo ullam velit cumque omnis blanditiis magnam neque quam excepturi sit sapiente possimus quos expedita doloremque, at fugiat commodi hic maxime alias? Nam, consectetur quos. Quidem odit, voluptates mollitia sapiente dolore illo porro sit maxime quae, aliquid suscipit ducimus dolor expedita, quos ipsum molestias ad eum vel.</p>
                <p>Deleniti itaque placeat laborum ipsum assumenda voluptates, rerum distinctio ducimus! Magni eveniet in eligendi molestiae ipsum optio ullam placeat assumenda non omnis libero consequuntur suscipit, odio iusto et iste ea, iure fugiat rerum quis? Illo rerum fugiat sed quod consequuntur reiciendis numquam optio ex veniam ad provident omnis iste vitae sunt quam, vero deserunt saepe ullam placeat! In, voluptatem nemo, distinctio porro sed omnis ea repellendus modi natus eligendi obcaecati ducimus. Laudantium enim, nostrum minus autem natus accusantium quos exercitationem?</p>
                <p>Harum, adipisci ut? Tempora illum totam soluta atque, ratione beatae quasi neque ipsa nostrum! A unde consequuntur hic quod voluptatem voluptatibus qui id dolore odit? Minima nesciunt hic, corporis possimus perspiciatis reiciendis reprehenderit, delectus consequatur cupiditate consequuntur voluptate, ratione sequi impedit! Voluptatum repellat laborum magni amet ullam quibusdam fugit provident quia exercitationem dicta excepturi, eveniet rem inventore dolor? Fuga ea saepe ex quis, eligendi fugit neque, voluptates pariatur minima blanditiis odio nulla voluptas qui nam excepturi? Soluta voluptatum voluptates magnam.</p>
                <p>Laborum, magnam nam, mollitia explicabo non blanditiis expedita necessitatibus ducimus illum minus facere officiis molestiae molestias temporibus ut deserunt. Voluptas nemo maiores repudiandae commodi et quibusdam dolore recusandae ducimus repellat repellendus maxime, minus alias quidem at aperiam ab eligendi laborum id atque, incidunt expedita. Sapiente ad illo distinctio cumque nobis fugit omnis sit voluptas eligendi, qui doloribus maxime ipsa. Deserunt iste aspernatur ipsa magni quisquam sed dolorem adipisci ab expedita rerum quod illo sint, vero obcaecati nulla repellat consequuntur facilis!</p>
                <p>Inventore alias fugit esse voluptates quas excepturi. Provident laboriosam asperiores inventore quae quibusdam at veniam, quia vitae repellendus expedita amet, ab debitis officia porro nemo quas dolores quasi iste necessitatibus ipsam odit nesciunt deleniti? Error omnis id nam voluptatibus ratione ad, laborum alias facere at laudantium sunt laboriosam voluptas tenetur quia vitae repudiandae sequi mollitia eum nisi doloribus perferendis. Sequi, ratione consequatur? Perferendis maxime nobis, adipisci modi quia tempore harum odio veniam in doloremque sunt minus impedit perspiciatis, sapiente eligendi!</p>

            </div>
        </section>
    )
}

export default Inversiones